services:
  server:
    container_name: emcable_nginx
    build: ./server
    restart: always
    networks:
      - emcablenet
    ports:
      - "5431:80"

  app:
    container_name: emcable_api_app
    build: ./app
    restart: always
    ports: 
      - "5432:5432"
    networks:
      - emcablenet
    depends_on:
      - server

networks:
  emcablenet:
    driver: bridge