services:
  nginx:
    image: nginx
    container_name: emcable_nginx
    restart: always
    networks:
      - emcablenet
    ports:
      - "8880:80"
    volumes:
      - ./nginx/emcable.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    container_name: emcable_app
    build: ./app
    restart: always
    networks:
      - emcablenet
    depends_on:
      - nginx

networks:
  emcablenet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450